name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    # paths:
    #   - 'docs/**.md'
    #   - 'docs/images/**'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - name: Install converter
        run: |
          echo "::group::My title"
          sudo apt install pandoc -y
          sudo apt-get install curl
          npm i -g mermaid-filter
          sudo apt-get -y install texlive-latex-recommended texlive-pictures texlive-latex-extra texlive-fonts-recommended
      - name: Test path
        run : |
          pwd
          ls -a
          ls ./docs/ -a
        working-directory: main
      - name: Create PDF
        run : |
          mkdir pdfs
          pandoc  -F mermaid-filter -o ./pdfs/requirements.pdf ./docs/requirements.md
        working-directory: main
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: pdfs
